### ISSUE TITLE
Make front proxy ingress paths configurable

### ISSUE THREAD

**Issue by martivo** [kcp-dev/helm-charts#134]
We serve multiple services from the same host as the KCP front proxy. It would be desired to be able to configure the ingress paths that are to be sent to KCP front proxy. Our current manually created ingress for KCP has the paths for /clusters and /services. At the moment we have disabled the creation of Ingress by the KCP chart and create it separately as a workaround.
```
  rules:
    - host: XXX
      http:
        paths:
          - path: /clusters
            pathType: Prefix
            backend:
              service:
                name: kcp-front-proxy
                port:
                  number: 8443
          - path: /services
            pathType: Prefix
            backend:
              service:
                name: kcp-front-proxy
                port:
                  number: 8443
```
If this is acceptable I could create the PR. The values file would be something like this: 
```
kcpFrontProxy:
    ingress:
      paths:
      - /clusters
      - /services
```
The default would remain "/" and be backwards compatible. Would this be a good improvement?
